platform :ios, '15.0'
use_frameworks!

# Target definition for HOTSPOT PLUS (com.hotspotplus.app)
target 'App' do
  capacitor_pods = [
    '@capacitor/core',
    '@capacitor/ios',
    '@capacitor/filesystem',
    '@capacitor/preferences',
    '@capacitor/share',
    '@capacitor/haptics'
  ]

  # Pods for App
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
